include:
    - ./proxy.yaml
services:
    web:
      depends_on:
         db:
           condition: service_healthy
      build:
        context: .
        dockerfile: Dockerfile.python
      networks:
         backend:
           ipv4_address: 172.20.0.5
      env_file:
        - .env
      environment:
         - DB_NAME=${MYSQL_DATABASE}
         - DB_USER=${MYSQL_USER}
         - DB_PASSWORD=${MYSQL_PASSWORD}
         - DB_HOST=db
     
      restart: always

    db:
      image: mysql:8
      networks:
         backend:
           ipv4_address: 172.20.0.10
      env_file:
        - .env
      environment:
         - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
         - MYSQL_DATABASE=${MYSQL_DATABASE}
         - MYSQL_USER=${MYSQL_USER}
         - MYSQL_PASSWORD=${MYSQL_PASSWORD}
         - MYSQL_ROOT_HOST="%"
      restart: always
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
        interval: 10s
        timeout: 10s
        retries: 10




     
         
     
    
      

       
